### ISSUE TITLE
Example usage of notebooks/wiggle.py

### ISSUE THREAD

**Issue by snitramodranoel** [stuliveshere/PySeis-archive#2]
Hi, I have been trying to understand your `wiggle.py` implementation of wiggle charts since I've reached this source code from a post on StackExchange. I was wondering if you could add a small dataset (two traces would do it) so that I could inspect the contents of the `frame` input argument to `wiggle()`.

Thank you very much.

**Comment by stuliveshere** [comment]
the dataset is an SU (seismic unix) which has been directly mapped into numpy using a numpy structured array defined in PySeis.su. 

but for this case you can hack a dtype directly, since the array only has 2 fields
- 'ns': number of samples
- 'trace': defines the trace format, i.e.('trace', ('f4',ns))

Hope that helps.

**Comment by snitramodranoel** [comment]
It helps a lot @stuliveshere 

Thank you very much.
